### ISSUE TITLE
PluginValidationError with pytest 8.1.0

### ISSUE THREAD

**Issue by hairmare** [stephrdev/pytest-isort#50]
The recently released pytest 8.1.0 removed the `path` argument to `pytest_collect_file` resulting in this error for plugins that didn't use the new `file_path` arg. 

```
pluggy._manager.PluginValidationError: Plugin 'flake8' for hook 'pytest_collect_file'
hookimpl definition: pytest_collect_file(file_path, path, parent)
Argument(s) {'path'} are declared in the hookimpl but can not be found in the hookspec
```

`file_path` was supported starting with version 7.0.0 of pytest.

**Comment by stephrdev** [comment]
released 4.0.0. Should fix the issues thanks to your PRs. Great!

**Comment by hairmare** [comment]
Thanks for the quick turnaround!

**Comment by hairmare** [comment]
btw, 8.1.0 was yanked in the meantime: https://github.com/pytest-dev/pytest/issues/12069

i'm still trying to figure out what this affects, but it looks like 4.0.0 won't be installable until pytest fixes this.

**Comment by stephrdev** [comment]
but it should work with pyrest 8.0 until then i think, right?

**Comment by hairmare** [comment]
as well as with 8.1.0 if you got it before it was yanked :+1:
