### ISSUE TITLE
Do not install additional LICENSE.rst

### ISSUE THREAD

**Issue by moubctez** [stephrdev/pytest-isort#54]
For me v4.0.0 installs `LICENSE.rst` directly into `site-packages` directory. There is already `LICENSE.rst` in `site-packages/pytest_isort-4.0.0.dist-info/LICENSE.rst`. This patch solves the issue:

```
--- pyproject.toml.orig	2024-04-12 09:55:54.110167676 +0000
+++ pyproject.toml
@@ -26,7 +26,6 @@ classifiers = [
 	"Framework :: Pytest",
 ]
 packages = [{ include = "pytest_isort" }]
-include = ["LICENSE.rst"]
 
 [tool.poetry.plugins.pytest11]
 isort = "pytest_isort"
```

**Comment by stephrdev** [comment]
Thank you for the hint, committed a change. Next release will include the fix.
